const { config } = require("dotenv");

config();

const PORT = process.env.PORT || 3000;

const NODE_ENV = process.env.NODE_ENV;

const ROOT_USER = process.env.ROOT_USER;
const ROOT_PASSWORD = process.env.ROOT_PASSWORD;

const DATABASE_HOST = process.env.DATABASE_HOST || "127.0.0.1";
const DATABASE_NAME = process.env.DATABASE_NAME;
const DATABASE_USER = process.env.DATABASE_USER;
const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD;

const LOGOUT_TIME = process.env.LOGOUT_TIME || 30;

const SECRET_WORD = process.env.SECRET_WORD;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

const CLOUD_PAGE_URL = process.env.CLOUD_PAGE_URL;
const CLOUD_PAGE_SECRET_CODE_SYNC = process.env.CLOUD_PAGE_SECRET_CODE_SYNC;

module.exports = {
	PORT,
	NODE_ENV,
	LOGOUT_TIME,

	DATABASE_HOST,
	DATABASE_NAME,
	DATABASE_USER,
	DATABASE_PASSWORD,

	ROOT_USER,
	ROOT_PASSWORD,
	SECRET_WORD,

	CLOUDINARY_CLOUD_NAME,
	CLOUDINARY_API_KEY,
	CLOUDINARY_API_SECRET,

	CLOUD_PAGE_URL,
	CLOUD_PAGE_SECRET_CODE_SYNC,
};
